### ISSUE TITLE
504 Timeout Error

### ISSUE THREAD

**Issue by princevash** [batdan/midjourney-api-php#2]
Hello,
I'm getting 504 Timeout Error after the image is generated.
The API is working fine and the prompt is being sent to discord server but at the time of showing imageurl, the script goes timeout.

**Comment by batdan** [comment]
Hello,
I just increased the wait times in release v2.1.1
Let me know if it's good for you.

Have a good day
Daniel

**Comment by batdan** [comment]
"504 Timeout Error"

I hadn't realized, but a 504 is obtained on a browser.
I advise you to run this script with PHP CLI

If you absolutely want to use the module on a browser, it will probably be necessary to increase the execution time of the scripts on the PHP server.

Generating an image takes about a minute

"504 Timeout Error"

I hadn't realized, but a 504 is obtained on a browser.
I advise you to run this script with PHP CLI

If you absolutely want to use the module on a browser, it will probably be necessary to increase the execution time of the scripts on the PHP server.

Generating an image takes about a minute

I advise you to add an instruction on your PHP file which is at the origin of the creation of the image:

```
<?php
ini_set('max_execution_time', 300);
```
