### ISSUE TITLE
Ephemeral Messages

### ISSUE THREAD

**Issue by leonardooleg** [batdan/midjourney-api-php#5]
Midjourney bot send ephemeral (private) messages  and when the images are ready - the script cannot receive this message in the chat

**Comment by batdan** [comment]
to receive images in a private chat, it must be configured to use Midjourney.
It can only work with a paid plan.
just do /imagine in this private Discord chat to see if that's the case.
Once this first step has been validated, all you have to do is right-click on this channel to retrieve its ID.
This package is designed to also work with private channels

**Comment by leonardooleg** [comment]
I found the problem is shadow answers with forbidden words in the query.
https://drive.google.com/file/d/1TaL5JlDuSwlYpbAAxQHax8pCc7hWBGqu/view?usp=drivesdk
