### ISSUE TITLE
concurrent fast jobs limit

### ISSUE THREAD

**Issue by liorphp** [batdan/midjourney-api-php#6]
I have account with 3 concurrent fast jobs.
On discord, i can send more then 3 prompts.  The fourth and beyond just wait in queue.

But in your code it can't send more than 3 prompts at the same time. If I send 4, the fourth one just doesn't send. If I want to send another prompt, I have to wait...

Can this be solved? Maybe a different configuration on 'interactions' post.
Or is it not possible here?

Thsnks!

**Comment by batdan** [comment]
Hi,

I was not aware of this limitation of 3 simultaneous image creations.
I added a waiting mechanism to not send more than 3 images at the same time.
The wait is currently set at 15 minutes but might not be enough if the queue is long.

Please test and let me know if everything works.

Realease: v2.1.4

**Comment by liorphp** [comment]
In my opinion, the solution is not correct, because if this was the problem I would simply purchase a larger package that has a limit of 12 photos at the same time.

I put it in the queue.

But in your API it just can't get it into that queue.
So I asked, maybe it's something related to interactions parameters.

**Comment by batdan** [comment]
I share your opinion, the solution is not optimal, but I currently do not have time to look more seriously at this question.
Discord's API documentation is awful and I know in advance that I'm going to spend a lot of time to come up with a workable solution that takes into account the specifics of the plans offered by Midjourney.

If you have time, you can offer me a Pull Request.

I already know that I will not be able to invest myself in such an evolution before September
